name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  release:
    name: Create Release
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set build variables
        run: |
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.x'
      - name: Get packages
        uses: actions/download-artifact@v3
        with:
          name: packages
          path: dist
      - name: Install packages
        run: pip install dist/*.whl
      - name: Check version number
        # Check that the setuptools_scm-generated version number is still the same when
        # installed from a wheel with setuptools_scm not present.
        run: |
          set -x
          test $(briefcase --version) = $VERSION
      - name: Create Release
        uses: ncipollo/release-action@v1.11.2
        with:
          name: ${{ env.VERSION }}
          draft: true
          artifacts: dist/*
          artifactErrorsFailBuild: true
      - name: Publish release to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
